// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_bYMBDSA_8xfh_EO7PETLa5evcADtG2g',
    appId: '1:873077109903:web:f6decdfb773d10e23decfa',
    messagingSenderId: '873077109903',
    projectId: 'cashinvest-42f6f',
    authDomain: 'cashinvest-42f6f.firebaseapp.com',
    storageBucket: 'cashinvest-42f6f.appspot.com',
    measurementId: 'G-BMFFN3L7XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPz8V0fH5mFuskT7ZdicRoH92XMThdzss',
    appId: '1:873077109903:android:b1ae2cf2f5b1255f3decfa',
    messagingSenderId: '873077109903',
    projectId: 'cashinvest-42f6f',
    storageBucket: 'cashinvest-42f6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFgW4ilPRO_WVq6gNFn5q8u13RrBzRHE',
    appId: '1:873077109903:ios:a44bf85cdf39f1ff3decfa',
    messagingSenderId: '873077109903',
    projectId: 'cashinvest-42f6f',
    storageBucket: 'cashinvest-42f6f.appspot.com',
    iosBundleId: 'com.example.cashInvest',
  );
}
